home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
	path('', views.home, name='home'),
    path('/project', views.project, name='project'),
    path('/story', views.story1, name='story'),
    path('/matkul', views.matkul, name='matkul')
]

matkul/urls.py
from django.urls import path
from . import views

appname = 'matkul'

urlpatterns = [
    path('', views.jadwal),
    path('<int:pk>/', views.delete, name = 'hapus'),
    
]

story5/story5/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('home.urls')),
    path('', include('matkul.urls'))
]

home/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models

class Matkul(models.Model):
    nama_mata_kuliah = models.CharField(blank=False, max_length = 100)
    nama_dosen = models.CharField(blank=False, max_length=100)
    jumlah_sks = models.CharField(blank=False, max_length = 3)
    deskripsi_mata_kuliah = models.CharField(blank=False, max_length = 200)
    tahun_semester = models.CharField(blank=False, max_length = 50)
    ruang_kelas = models.CharField(blank=False, max_length = 100)

matkul/forms.py
from django import forms

class formulir(forms.Form):
    nama_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    nama_dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True
    }))
    deskripsi_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    tahun_semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester Tahun (ex. Gasal 2019/2020)',
        'type' : 'text',
        'required' : True
    }))
    ruang_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Lokasi Ruang Kelas',
        'type' : 'text',
        'required' : True
    }))

home/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'home.html')

def project(request):
	return render(request, 'project.html')

def story1(request):
	return render(request, 'story1.html')

def matkul(request):
	return render(request, 'index.html')

matkul/views.py
from django.shortcuts import render, redirect
from . import forms, models

def jadwal(request):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if (context.is_valid()):
            context1 = models.Matkul()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("/")
    else:
        context = forms.formulir()
        context1 = models.Matkul.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal' : context1
        }
    return render(request, 'template_matkul/index.html', context_dictio)
    

def delete(request, pk):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if(context.is_valid()):
            context1 = models.Matkul()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("/")
    else:
        models.Matkul.objects.filter(pk = pk).delete()
        context = forms.formulir()
        context1 = models.Matkul.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal' : context1
        }
        return render(request, 'template_matkul/index.html', context_dictio)

home/templates/template_home/base.html
{% load static %}

<!DOCTYPE html>
<html lan="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    {% block style %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>
        {% block title %} {% endblock %}
    </title>

</head>

<body>

    <div class="container navbar">
        <header>
            <div class="logo">
                <h1>Jsaon</h1>
            </div>

            <nav>
                <ul>
                    <li><a href="#about">About Me</a></li>
                    <li><a href="#hobbies">Hobbies</a></li>
                    <li><a href="{% url 'home:project' %}">Project</a></li>
                    <li><a href="{% url 'home:story' %}">Profile</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </header>
    </div>


    {% block content %}
    {% endblock %}


    <footer>
        <div class="container contact" id="contact">
            <p>Mind send me a message? Sweet!</p>
        </div>
        <div class="container arrow">
            <a href="#">
                <img src="{% static 'img/arrow.png' %}" alt="pict error" width="25">
            </a>
        </div>
        <div class="container logo">
            <span><a href="https://www.linkedin.com/in/johanes-jason-155220195/" target="_blank">
                <img src="{% static 'img/LinkedIn Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://www.instagram.com/knightrexyz/" target="_blank">
                <img src="{% static 'img/IG Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://steamcommunity.com/id/jsaonn/" target="_blank">
                <img src="{% static 'img/Steam Logo.png' %}" alt="pict error" width="25">
            </a></span>
            <span><a href="https://gitlab.com/Jsaonn/" target="_blank">
                <img src="{% static 'img/Gitlab Logo.png' %}" alt="pict error" width="25">
            </a></span>
        </div>
    </footer>
</body>
</html>

home/templates/template_home/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}Jsaon's Web{% endblock %}


{% block content %}
    <div class="container homepage">
        <div class="text">
            <h1>
                <span>Hello there.</span>
                <br>
                <div>
                    <span>My name is</span>
                    <span class="name">J</span>
                    <span class="m-left name">s</span>
                    <span class="m-left name">a</span>
                    <span class="m-left name">o</span>
                    <span class="m-left name">n</span>
                    <span class="m-left name">,</span>
                </div>
                <br>
                <span>I'm a human.</span>
                <a href="#about">Explore more</a>
            </h1>
        </div>
    </div>

    <div class="container about" id="about">
        <div class="text-about">
            <h1>
                About me
            </h1>
        </div>
        <div class="about-me-text">
            <p>I called Jsaon, and I am second-year student of Computer Science at University of Indonesia.</p>
            <p>I usually read manga everyday, and I dedicated my life for sleep.</p>
        </div>
        <div class="profile-image">
            <img src="{% static 'img/Profile.png' %}" alt="This text is shown if server fails to load image" />
        </div>
    </div>

    <div class="container hobbies" id="hobbies">
        <div class="text-hobbies">
            <h1>Hobbies</h1>
        </div>
        <div class="hobbies-info">
            <div class="hobby">
                <img src="{% static 'img/FPS Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>FPS Games</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Psy Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Psychology</h1></div>
            </div><br>
            <div class="hobby">
                <img src="{% static 'img/Sleep Logo.png' %}" alt="This text is shown if server fails to load image" />
                <div class="desc"><h1>Sleep</h1></div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/template_home/project.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}Jsaon's Project{% endblock %}

{% block content %}
        <div class="container coming-soon">
            <a href="{% url 'home:matkul' %}"><h1>Jadwal Kuliah!</h1></a>
            <br>
            <a href="{% url 'home:home' %}">back</a>
        </div>
{% endblock %}

home/templates/template_home/story1.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<!-- <link rel="stylesheet" type="text/css"  href="{% static 'css/style2.css' %}"> -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
{% endblock %}

{% block title %}Story 1 PPW{% endblock %}


{% block content %}
    <div class="story1">
        <div>
            <h2 align="center">Welcome to my website!</h2>
        </div>

        <hr/>
        <br/>

        <div>
            <div>
                <div><img src="{% static 'img/pic1.jpg' %}" alt="pict error" class="rounded-circle" width="150"></div>
                <div class="text-black h3"><h3>Jaenhos Jsaon</h3></div>
            </div>
        </div><br/>

        <div>
            <h3>
                <div><b>About me :</b></div>
                <div>Second year student of Computer Science at Universitas Indonesia</div>
                <div>Passionate about psychology, mental development, and programming</div>
            </h3>
        </div><br/>

        <div>
            <h3>
                <b>Profile :</b>
                <ul>
                    <li>NPM 1906293120</li>
                    <li>Maung 2019</li>
                    <li>Computer Science, University of Indonesia</li>
                </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
                <b>Hobbies :</b>
                <ul>
                    <li>Gaming</li>
                    <li>Sleep</li>
                </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
            <div><b>Education :</b></div>
            <ul>
                <li>SMAN 13 Jakarta</li>
                <li>Universitas Indonesia</li>
            </ul>
            </h3>
        </div><br/>

        <div>
            <h3>
                <div><b>You can find me at :</b></div>
                <div>
                    <a href="https://www.instagram.com/knightrexyz/?hl=en" target="_blank">
                    <span><img src="{% static 'img/ig-logo.png' %}" alt="pict error" width="25"></span>
                    </a>
                    <a href="https://www.linkedin.com/in/johanes-jason-155220195/" target="_blank">
                    <span><img src="{% static 'img/linkedin-logo.png' %}" alt="pict error" width="25"></span>
                    </a>
                </div>
            </h3>
        </div>

        <div class="container back">
            <a href="{% url 'home:home' %}">back</a>
        </div>
    </div>
    {% endblock %}

matkul/templates/template_matkul/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d5ac12ca84.js"></script>

    <title>Jadwal Ashoy</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"><h3>Jadwal Mata Kuliah</h1></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                Jaenhos Jsaon
                </li>
            </ul>
            </div>
        </div>
    </nav>
<section class="inputJadwal" id="inputJadwal">
    <div class="container pt-5 pb-3 justify-content">
        <div class="row pt-5">
            <div class="card text-white bg-dark mb-3 pb-3 text-center" style="max-width: 18rem;">
                <div class="card text-white bg-dark mb-3 pb-3 text-center" style="max-width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title"><h2><b>Susun Matkul</b></h2></h5>
                      <p class="card-text"><i>Fitur ini digunakan untuk list nama mata kuliah sesuai yang diambil oleh mahasiswa</i></p>
                    </div>
                </div>
                <h5 class="card-title"><h2><b>Disusun oleh :</b></h2></h5>
                <p class="card-text"><i>Johanes Jason, dalam rangka menyelesaikan tugas Story 5 Perancangan dan Pemograman Web</i></p>
                <p class="card-text"><i>Website ini dikerjakan berbarengan dengan TP SDA yang mengakibatkan kurang tidur</i></p>
            </div>
            <div class="col-md-6">
                <form action="" method="POST" class="ml-5">
                    {% csrf_token %}
                    {{ formulir }}
                    <div class = "centre-items" style = "margin-top: 2%">
                        <input type = "submit" class="btn btn-dark" value="Submit"> 
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="cekjadwal" id="cekjadwal">
    <div class="table-responsive" id="Table">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nama Mata Kuliah</th>
                    <th scope="col">Nama Dosen</th>
                    <th scope="col">Jumlah SKS</th>
                    <th scope="col">Deskripsi Mata Kuliah</th>
                    <th scope="col">Tahun Semester</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col"></th>
                </tr>
            </thead>

            {% for i in jadwal %}
            <tbody>
                <tr>
                    <td>{{i.nama_mata_kuliah}}</td>
                    <td>{{i.nama_dosen}}</td>
                    <td>{{i.jumlah_sks}}</td>
                    <td>{{i.deskripsi_mata_kuliah}}</td>
                    <td>{{i.tahun_semester}}</td>
                    <td>{{i.ruang_kelas}}</td>
                    <td>
                
                    <a  href = "{% url 'hapus' pk=i.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i>
                    </button></a>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
            
        </table>

    
</section>

<footer class="bg-dark">
    <div class="container mt-3">
        <div class="row pt-1">
            <div class="col text-center text-white">
                <i>keqing best waifu</i>
            </div>
        </div>
    </div>
</footer>
    
  </body>
</html>